/**
* @File Name          : OpportunityTriggerHandler.cls
* @Description        : Trigger handler class for Opportuntiy (Enquiry)
* @Author             :
* @Group              :
* @Last Modified By   : Rajesh Ramachandran
* @Last Modified On   : 1/20/2020, 11:26:51 AM
* @Modification Log   :
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0    7/05/2019, 9:14:54 PM                                Initial Version
1.1    26/08/2019, 9:14:54 AM        Sunit                  checkBookingCancellationReason method is added
1.2    09/12/2019                    subhojit               Added dummy account creation logic
1.3    18/07/2020					Nitish/Anuj				Logic move to Strategy design pattern (L2 Team to delete this class)
**/

//CODE REVIEWED BY: Prabhat Sharma


public without sharing class OpportunityTriggerHandler extends TriggerHandler {
}